# Generated by Django 4.0.3 on 2022-03-31 09:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('post_ptr', models.OneToOneField(
                    auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True, primary_key=True, serialize=False, to='posts.post')),
                ('resume_file',
                 models.FileField(upload_to='files',
                                  validators=[django.core.validators.FileExtensionValidator(
                                      allowed_extensions=['pdf'])])),
            ],
            bases=('posts.post',),
        ),
    ]
