# Generated by Django 4.0.3 on 2022-03-31 11:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_poll'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(
                    default=None, upload_to='files',
                    validators=[django.core.validators.FileExtensionValidator(
                        allowed_extensions=['pdf', 'png', 'jpg', 'jpeg'])])),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.poll')),
            ],
        ),
    ]
