# Generated by Django 4.0.3 on 2022-03-26 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0002_rename_ammountofvoters_poll_amountofvoters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='firstFile',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='fourthFile',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='secondFile',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='thirdFile',
        ),
        migrations.CreateModel(
            name='PollFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.BinaryField()),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Feed.poll')),
            ],
        ),
    ]
