# Generated by Django 4.0.3 on 2022-03-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0003_remove_poll_firstfile_remove_poll_fourthfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollfile',
            name='file',
            field=models.FileField(default=None, upload_to='False/<built-in function id>/'),
        ),
    ]
