# Generated by Django 4.0.3 on 2022-03-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0004_alter_pollfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollfile',
            name='file',
            field=models.FileField(default=None, upload_to='files'),
        ),
    ]
