# Generated by Django 4.0.3 on 2022-03-26 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0005_alter_pollfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollfile',
            name='file',
            field=models.FileField(
                default=None, upload_to='files',
                validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]
                ),
        ),
    ]
