# Generated by Django 4.0.3 on 2022-03-26 15:24

from django.db import migrations, models
import userProfile.models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_remove_userprofile_id_userprofile_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.CharField(
                max_length=30,
                primary_key=True,
                serialize=False,
                unique=True,
                validators=[userProfile.models.validate_email_addr]
                ),
        ),
    ]
